name: Build

on:
  push:
  pull_request:

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew assembleRelease
        # Upload all build artifacts in separate steps. This can be shortened once https://github.com/actions/upload-artifact/pull/354 is merged.
      - name: Upload artifact findroid-libre-arm64-v8a.apk
        uses: actions/upload-artifact@v4
        with:
          name: findroid-libre-arm64-v8a.apk
          path: ./app/phone/build/outputs/apk/libre/release/findroid-libre-arm64-v8a.apk
      - name: Upload artifact findroid-libre-armeabi-v7a.apk
        uses: actions/upload-artifact@v4
        with:
          name: findroid-libre-armeabi-v7a.apk
          path: ./app/phone/build/outputs/apk/libre/release/findroid-libre-armeabi-v7a.apk
      - name: Upload artifact findroid-libre-x86_64.apk
        uses: actions/upload-artifact@v4
        with:
          name: findroid-libre-x86_64.apk
          path: ./app/phone/build/outputs/apk/libre/release/findroid-libre-x86_64.apk
      - name: Upload artifact findroid-libre-x86.apk
        uses: actions/upload-artifact@v4
        with:
          name: findroid-libre-x86.apk
          path: ./app/phone/build/outputs/apk/libre/release/findroid-libre-x86.apk

